#! /usr/bin/env python3

import monitor, mailer, os, time, logging, yaml

class MonitorApp():

    def __init__(self, config):
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.DEBUG)
        formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
        handler = logging.FileHandler(config['log']['file'])
        handler.setFormatter(formatter)
        self.logger.addHandler(handler)
        self.notifier = mailer.Mailer(config['mailer']['smtphost'])
        self.monitors = []
        for mon in config['monitors']:
            self.logger.info("Adding monitor " + mon['name'])
            self.monitors.append(monitor.Monitor(self.notifier, mon['name'], mon['host'], mon['find_string'], mon['port']))

    def run(self):
        self.logger.info("Checking monitor")
        for mon in self.monitors:
            mon.check()

if __name__ == "__main__":
    with open('monitor.yml', 'r') as ymlfile:
        config = yaml.load(ymlfile)
    monitor_app = MonitorApp(config)
    monitor_app.run()
